// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// update_rho_all_rcpp
arma::mat update_rho_all_rcpp(const arma::mat& X, const arma::mat& Fuv, const arma::vec& s, const arma::mat& mu, const arma::mat& L, const arma::mat& rho, unsigned int maxiter, double tol, double maxrho);
RcppExport SEXP _poisson_mash_alpha_update_rho_all_rcpp(SEXP XSEXP, SEXP FuvSEXP, SEXP sSEXP, SEXP muSEXP, SEXP LSEXP, SEXP rhoSEXP, SEXP maxiterSEXP, SEXP tolSEXP, SEXP maxrhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Fuv(FuvSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type s(sSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type maxrho(maxrhoSEXP);
    rcpp_result_gen = Rcpp::wrap(update_rho_all_rcpp(X, Fuv, s, mu, L, rho, maxiter, tol, maxrho));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_poisson_mash_alpha_update_rho_all_rcpp", (DL_FUNC) &_poisson_mash_alpha_update_rho_all_rcpp, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_poisson_mash_alpha(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
