# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call('_poisson_mash_alpha_rcpparma_hello_world', PACKAGE = 'poisson.mash.alpha')
}

rcpparma_outerproduct <- function(x) {
    .Call('_poisson_mash_alpha_rcpparma_outerproduct', PACKAGE = 'poisson.mash.alpha', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('_poisson_mash_alpha_rcpparma_innerproduct', PACKAGE = 'poisson.mash.alpha', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('_poisson_mash_alpha_rcpparma_bothproducts', PACKAGE = 'poisson.mash.alpha', x)
}

