# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

update_rho_all_rcpp <- function(X, Fuv, s, mu, L, rho, maxiter, tol, maxrho) {
    .Call('_poisson_mash_alpha_update_rho_all_rcpp', PACKAGE = 'poisson.mash.alpha', X, Fuv, s, mu, L, rho, maxiter, tol, maxrho)
}

